# Label definitions for OpenSpec workflows
labels:
  - name: "spec"
    color: "0E8A16"
    description: "Specification issues"
  - name: "proposal"
    color: "1D76DB"
    description: "Proposal documents"
  - name: "implementation"
    color: "5319E7"
    description: "Implementation pull requests"
  - name: "spec:draft"
    color: "FBCA04"
    description: "Work in progress specs"
  - name: "spec:approved"
    color: "0E8A16"
    description: "Approved and ready for implementation"
  - name: "spec:implemented"
    color: "0B5345"
    description: "Fully implemented specs"
  - name: "needs-spec"
    color: "D93F0B"
    description: "PR missing spec reference"
  - name: "scope-creep"
    color: "B60205"
    description: "Changes beyond spec scope"
