name: "Proposal"
description: "Describe how to implement an approved spec."
title: "Proposal: "
labels:
  - "proposal"
body:
  # Overview
  - type: markdown
    attributes:
      value: |
        Use this form to propose an implementation approach for an approved spec.
        Reference the spec issue and link to any OpenSpec change details.

  # Related Spec
  - type: input
    id: related_spec
    attributes:
      label: Related Spec
      description: "Required spec issue reference."
      placeholder: "Spec issue: #123"
    validations:
      required: true

  # Proposed Approach
  - type: textarea
    id: proposed_approach
    attributes:
      label: Proposed Approach
      description: "How will you implement the spec?"
      placeholder: "Outline the architecture, components, and sequence."
    validations:
      required: true

  # Alternatives Considered
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: "What other approaches were evaluated?"
      placeholder: "List options and why they were rejected."

  # Trade-offs
  - type: textarea
    id: tradeoffs
    attributes:
      label: Trade-offs
      description: "List trade-offs and expected impacts."

  # Implementation Plan
  - type: textarea
    id: implementation_plan
    attributes:
      label: Implementation Plan
      description: "Phases, milestones, or rollout steps."
      placeholder: "Phase 1: ..."
    validations:
      required: true

  # Risks and Mitigations
  - type: textarea
    id: risks
    attributes:
      label: Risks and Mitigations
      description: "Identify risks and how they will be mitigated."
