name: Release bundle
on: { push: { tags: ["v*.*.*", "v*.*", "v*"] } }
permissions: { contents: write }
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.0
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.0.0
        with: { node-version: 20, cache: "npm" }
      - run: npm ci || npm i
      - run: npm run build
      - run: cd dist && zip -r ../artagon-site-dist.zip .
      - uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.x
        with: { files: artagon-site-dist.zip, generate_release_notes: true }
